import * as Feather from 'react-icons/fi';
import { FcGoogle } from 'react-icons/fc';

export const ICONS = {
	'x': Feather.FiX,
	'google': FcGoogle,
	'tag': Feather.FiTag,
	'key': Feather.FiKey,
	'map': Feather.FiMap,
	'user': Feather.FiUser,
	'mail': Feather.FiMail,
	'lock': Feather.FiLock,
	'hash': Feather.FiHash,
	'flag': Feather.FiFlag,
	'plus': Feather.FiPlus,
	'link': Feather.FiLink,
	'file': Feather.FiFile,
	'home': Feather.FiHome,
	'edit': Feather.FiEdit3,
	'truck': Feather.FiTruck,
	'minus': Feather.FiMinus,
	'phone': Feather.FiPhone,
	'check': Feather.FiCheck,
	'log-in': Feather.FiLogIn,
	'trash': Feather.FiTrash2,
	'search': Feather.FiSearch,
	'unlock': Feather.FiUnlock,
	'log-out': Feather.FiLogOut,
	'map-pin': Feather.FiMapPin,
	'card': Feather.FiCreditCard,
	'bag': Feather.FiShoppingBag,
	'package': Feather.FiPackage,
	'calendar': Feather.FiCalendar,
	'cart': Feather.FiShoppingCart,
	'refresh': Feather.FiRefreshCw,
	'file-text': Feather.FiFileText,
	'currency': Feather.FiDollarSign,
	'arrow-left': Feather.FiArrowLeft,
	'message': Feather.FiMessageSquare,
	'arrow-right': Feather.FiArrowRight
};
